{% set name = "offlineimap" %}
{% set version = "8.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OfflineIMAP/offlineimap3/archive/v{{ version }}.tar.gz
  sha256: c299cbbab92d48215ea37ec06ec68699d17e59ab97a1b98e792f75e0a507b306

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - rfc6555
    - imaplib2
    - urllib3 >=1.25.9,<1.26
    - distro

test:
  imports:
    - offlineimap
    - offlineimap.folder
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.offlineimap.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'Read/sync your IMAP mailboxes'
  description: |
    OfflineIMAP is software that downloads your email mailbox(es) as 
    local Maildirs. OfflineIMAP will synchronize both sides via IMAP.
  doc_url: http://www.offlineimap.org/documentation.html
  dev_url: https://github.com/OfflineIMAP/offlineimap

extra:
  recipe-maintainers:
    - jan-janssen
